export const styles = {
  width: "100%",
  display: "flex",
  flexDirection: "column",
  // border: "2px solid #7e797659",
  borderRadius: "3px",
  position: "relative",
  rowGap: "3px",
  row: {
    width: "100%",
    display: "flex",
    padding: "5px",
    fontSize: "22px",
    border: "3px solid #7e797659",
    borderRadius: "3px",
    backgroundColor: "#ddd2cc59",
    color: "#6f6161",
    outline: "none",
    fontSize: "17px",
    lineHeight: "1.4",
    whiteSpace: "break-spaces",
    wordBreak: "break-all",
    position: "relative",
    input: {
      position: "absolute",
      top: "50%",
      transform: "translateY(-50%)",
      left: "5px",
      width: "100%",
      opacity: "0",
      pointerEvents: "none",
    },
  },
};
