export const styles = {
  width: "100%",
  display: "flex",
  position: "relative",
  aspectRatio: 1 / 1.0991,
  overflow: "hidden",
  top: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    marginBottom: "13px",
    color: "#ff4600",
    fontSize: "18px",
    fontWeight: "bold",
    letterSpacing: "5px",
    flexShrink: 0,
    textTransform: "uppercase",
    year: {
      fontSize: "14px",
    },
  },
  days: {
    flexShrink: 0,
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "10px",
    color: "#ff4600ad",
    fontWeight: "bold",
    day: {
      width: `calc(100% / 7)`,
      textAlign: "center",
    },
  },
  list: {
    display: "flex",
    position: "absolute",
    left: "-100%",
    width: "300%",
    height: "calc(100% - 25px)",
    top: "25px",
  },
  month: {
    width: "calc(100% / 3)",
    height: "100%",
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    userSelect: "none",
    padding: "0px 8px",
    top: "0px",
    left: "0px",
  },
  weeks: {
    display: "flex",
    justifyContent: "space-between",
    flexWrap: "wrap",
    width: "100%",
    rowGap: "8px",
    day: {
      color: "#492e2e63",
      width: `calc(100% / 7)`,
      textAlign: "center",
      padding: "2px",
      currentMonth: {
        color: "#492e2e",
      },
      currentDay: {
        color: "#e10a0a",
        border: "1px solid #e8862d",
        borderRadius: "50%",
      },
      weekend: {
        color: "#b07151",
      },
    },
  },
  buttons: {
    position: "absolute",
    top: "0",
    left: "0",
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    button: {
      padding: "0px 0px",
      position: "relative",
      textTransform: "lowercase",
      color: "#41e717",
      letterSpacing: "2.2px",
      fontWeight: "600",
      fontSize: "14px",
      transition: "color .4s",
      userSelect: "none",
      hover: {
        color: "#ff4600ad",
        transition: "color .4s",
      },
      leave: {
        color: "#41e717",
        transition: "color .4s",
      },
      disabled: {
        color: "#7359345c",
        cursor: "not-allowed",
        transition: "color .4s",
        pointerEvents: "none",
      },
      undisabled: {
        cursor: "pointer",
        pointerEvents: "auto",
        transition: "color .4s",
        color: "#41e717",
      },
    },
    prev: {
      padding: "0px 20px 10px 0px",
    },
    next: {
      padding: "0px 0px 10px 20px",
    },
  },
};
